#.travis.yml

language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master
    - dev

before_script:
  - npm install -g firebase-tools

script:
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then REACT_APP_API_KEY=AIzaSyDnhjC9pfqqIvGObcUlN9KUIX7khkYpmBY REACT_APP_PROJ_NAME=cluckrdev npm build; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm build; fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then firebase deploy --project cluckrdev --token $FIREBASE_TOKEN; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then firebase deploy --project $REACT_APP_PROJ_NAME --token $FIREBASE_TOKEN; fi


notifications:
  email:
    on_failure: always
    on_success: always
